name: CI/CD pipeline for Lift-o-Meter

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Backend:
    runs-on: ubuntu-latest
    steps:
    - name: Get repo contents
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Maven clean install
      run: |
        cd back
        mvn clean install
    - name: Maven tests
      run: |
        cd back
        mvn test
  Frontend:
    runs-on: ubuntu-latest
    steps:
    - name: Get repo contents
      uses: actions/checkout@v2
    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: npm install
      run: |
        cd front
        npm install
    - name: Run tests
      run: |
        cd front
        npm test -- --watchAll=false
    
